import { StyleSheet } from 'react-native';

import { colors } from './theme';

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  loading: { flex: 1, backgroundColor: colors.ink },
  safeArea: { flex: 1, backgroundColor: colors.ink },
  appShell: { flex: 1, width: '100%', maxWidth: 520, alignSelf: 'center', backgroundColor: colors.ink, overflow: 'hidden' },
  ambientOrange: { position: 'absolute', width: 320, height: 320, borderRadius: 160, backgroundColor: '#7A210C', opacity: 0.23, right: -180, top: 60 },
  ambientAqua: { position: 'absolute', width: 260, height: 260, borderRadius: 130, backgroundColor: '#07535A', opacity: 0.18, left: -170, top: 540 },
  pageContent: { padding: 18, paddingBottom: 34 },
  pageContentWithBar: { padding: 18, paddingBottom: 120 },
  glassPanel: { overflow: 'hidden', borderWidth: 1, borderColor: colors.glassBorder, backgroundColor: colors.glass, borderRadius: 24 },
  glassContent: { flex: 1, flexDirection: 'row', alignItems: 'center' },
  header: { minHeight: 56, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 30 },
  headerTitle: { color: colors.white, fontSize: 21, fontWeight: '900', letterSpacing: -0.8 },
  headerCircle: { width: 44, height: 44, borderRadius: 22, borderWidth: 1, borderColor: colors.glassBorder, backgroundColor: colors.glass, alignItems: 'center', justifyContent: 'center' },
  headerDots: { color: colors.white, fontSize: 14, letterSpacing: 1 },
  backButtonText: { color: colors.white, fontSize: 34, lineHeight: 36, transform: [{ translateY: -2 }] },
  logoRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  wordmark: { color: colors.white, fontSize: 23, fontWeight: '900', letterSpacing: -1 },
  wordmarkSub: { color: colors.muted, fontFamily: 'IBMPlexMono_600SemiBold', fontSize: 7.5, letterSpacing: 1.4, marginTop: 2 },
  brandMark: { backgroundColor: colors.orange, alignItems: 'center', justifyContent: 'center' },
  brandMarkText: { color: colors.white, fontWeight: '900', letterSpacing: -6, transform: [{ translateX: -2 }, { translateY: -2 }] },
  eyebrow: { color: colors.orange, fontFamily: 'IBMPlexMono_600SemiBold', fontSize: 10, letterSpacing: 1.4, marginBottom: 10 },
  displayTitle: { color: colors.white, fontSize: 46, lineHeight: 48, fontWeight: '900', letterSpacing: -2.5 },
  displaySubtitle: { color: colors.muted, fontSize: 14, lineHeight: 21, maxWidth: 390, marginTop: 10, marginBottom: 22 },
  mapFrame: { height: 340, borderRadius: 30, overflow: 'hidden', borderWidth: 1, borderColor: colors.glassBorder, marginBottom: 12, backgroundColor: colors.surface },
  mapTopBadge: { position: 'absolute', left: 14, top: 14, minHeight: 30, borderRadius: 15, backgroundColor: 'rgba(8,8,10,0.78)', paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 7 },
  mapTopBadgeText: { color: colors.white, fontFamily: 'IBMPlexMono_600SemiBold', fontSize: 8, letterSpacing: 1.2 },
  liveDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.lime },
  selectedLocationCard: { minHeight: 82, padding: 13, marginBottom: 28 },
  locationNumber: { width: 48, height: 48, borderRadius: 16, backgroundColor: colors.orange, alignItems: 'center', justifyContent: 'center' },
  locationNumberText: { color: colors.white, fontFamily: 'IBMPlexMono_700Bold', fontSize: 16 },
  locationCopy: { flex: 1, marginLeft: 12, minWidth: 0 },
  locationName: { color: colors.white, fontFamily: 'IBMPlexMono_600SemiBold', fontSize: 9, letterSpacing: 1, textTransform: 'uppercase' },
  locationAddress: { color: colors.white, fontSize: 15, fontWeight: '800', marginTop: 3 },
  locationSchedule: { color: colors.aqua, fontFamily: 'IBMPlexMono_500Medium', fontSize: 9, marginTop: 5 },
  locationArrow: { color: colors.white, fontSize: 24, marginLeft: 8 },
  sectionLabel: { color: colors.muted, fontFamily: 'IBMPlexMono_600SemiBold', fontSize: 10, letterSpacing: 1.4, marginBottom: 10 },
  locationList: { gap: 8 },
  locationRow: { minHeight: 58, borderRadius: 18, backgroundColor: colors.glass, borderWidth: 1, borderColor: colors.glassBorder, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14 },
  locationRowActive: { borderColor: colors.orange, backgroundColor: 'rgba(255,75,24,0.12)' },
  locationRowIndex: { width: 38, color: colors.muted, fontFamily: 'IBMPlexMono_600SemiBold', fontSize: 11 },
  locationRowIndexActive: { color: colors.orange },
  locationRowAddress: { flex: 1, color: colors.white, fontSize: 13, fontWeight: '700' },
  radio: { width: 18, height: 18, borderRadius: 9, borderWidth: 1, borderColor: colors.muted },
  radioActive: { borderWidth: 5, borderColor: colors.orange },
  primaryButton: { minHeight: 62, borderRadius: 21, backgroundColor: colors.orange, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, marginTop: 14, shadowColor: colors.orange, shadowOpacity: 0.25, shadowRadius: 20, shadowOffset: { width: 0, height: 8 } },
  primaryButtonText: { color: colors.white, fontSize: 16, fontWeight: '900' },
  primaryButtonArrow: { color: colors.white, fontSize: 24 },
  pickupCard: { minHeight: 72, padding: 12, marginBottom: 14 },
  pickupPin: { width: 44, height: 44, borderRadius: 15, backgroundColor: colors.orange, alignItems: 'center', justifyContent: 'center' },
  pickupPinText: { color: colors.white, fontSize: 23 },
  pickupEyebrow: { color: colors.aqua, fontFamily: 'IBMPlexMono_600SemiBold', fontSize: 8, letterSpacing: 1, marginBottom: 4 },
  pickupAddress: { color: colors.white, fontSize: 14, fontWeight: '800' },
  changeText: { color: colors.orange, fontFamily: 'IBMPlexMono_600SemiBold', fontSize: 9 },
  heroPressable: { borderRadius: 30, overflow: 'hidden', marginBottom: 32 },
  hero: { height: 284, overflow: 'hidden', flexDirection: 'row' },
  heroGlow: { position: 'absolute', width: 210, height: 210, borderRadius: 105, backgroundColor: 'rgba(255,255,255,0.16)', right: -65, top: -75 },
  heroCopy: { width: '59%', padding: 22, zIndex: 2 },
  heroEyebrow: { color: 'rgba(255,255,255,0.78)', fontFamily: 'IBMPlexMono_700Bold', fontSize: 9, letterSpacing: 1.3, marginBottom: 18 },
  heroTitle: { color: colors.white, fontSize: 39, lineHeight: 37, fontWeight: '900', letterSpacing: -2.2 },
  heroDescription: { color: 'rgba(255,255,255,0.72)', fontSize: 11, lineHeight: 16, marginTop: 11, maxWidth: 150 },
  heroPricePill: { alignSelf: 'flex-start', backgroundColor: colors.white, borderRadius: 99, paddingHorizontal: 13, paddingVertical: 9, marginTop: 16 },
  heroPrice: { color: colors.ink, fontFamily: 'IBMPlexMono_700Bold', fontSize: 12 },
  heroProduct: { position: 'absolute', width: '58%', height: '120%', right: -34, bottom: -34, transform: [{ rotate: '7deg' }] },
  heroImage: { width: '100%', height: '100%' },
  sectionHeader: { flexDirection: 'row', alignItems: 'baseline', justifyContent: 'space-between', marginBottom: 15 },
  sectionTitle: { color: colors.white, fontSize: 34, fontWeight: '900', letterSpacing: -1.8 },
  sectionCounter: { color: colors.muted, fontFamily: 'IBMPlexMono_600SemiBold', fontSize: 9, letterSpacing: 1 },
  categories: { gap: 8, paddingRight: 18, marginBottom: 18 },
  categoryChip: { backgroundColor: colors.glass, borderWidth: 1, borderColor: colors.glassBorder, paddingHorizontal: 15, paddingVertical: 10, borderRadius: 99 },
  categoryChipActive: { backgroundColor: colors.white, borderColor: colors.white },
  categoryText: { color: colors.white, fontFamily: 'IBMPlexMono_500Medium', fontSize: 11 },
  categoryTextActive: { color: colors.ink, fontFamily: 'IBMPlexMono_700Bold' },
  grid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', rowGap: 12 },
  productCard: { width: '48.5%', borderRadius: 24, backgroundColor: colors.glass, borderWidth: 1, borderColor: colors.glassBorder, overflow: 'hidden' },
  pressed: { opacity: 0.76, transform: [{ scale: 0.985 }] },
  productVisual: { height: 164, overflow: 'hidden', alignItems: 'center', justifyContent: 'center' },
  productVisualHero: { height: 260, borderRadius: 28, marginBottom: 18 },
  productImage: { width: '100%', height: '126%', transform: [{ translateY: 13 }] },
  productImageHero: { height: '116%', width: '82%', transform: [{ translateY: 12 }] },
  productCopy: { padding: 13, paddingTop: 12 },
  productName: { minHeight: 40, color: colors.white, fontSize: 16, lineHeight: 19, fontWeight: '800' },
  productFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 8 },
  productPrice: { color: colors.muted, fontFamily: 'IBMPlexMono_600SemiBold', fontSize: 10 },
  addButton: { width: 34, height: 34, borderRadius: 17, backgroundColor: colors.orange, alignItems: 'center', justifyContent: 'center' },
  addButtonText: { color: colors.white, fontSize: 22, lineHeight: 24 },
  cartBarWrap: { position: 'absolute', left: 18, right: 18, bottom: 18 },
  cartBar: { minHeight: 66, borderRadius: 23, backgroundColor: 'rgba(24,24,28,0.84)', padding: 11 },
  cartCount: { width: 42, height: 42, borderRadius: 15, backgroundColor: colors.orange, alignItems: 'center', justifyContent: 'center' },
  cartCountText: { color: colors.white, fontFamily: 'IBMPlexMono_700Bold', fontSize: 13 },
  cartLabel: { flex: 1, color: colors.white, fontSize: 16, fontWeight: '800', marginLeft: 12 },
  cartTotal: { color: colors.white, fontFamily: 'IBMPlexMono_700Bold', fontSize: 13 },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'flex-end', alignItems: 'center' },
  modalDismiss: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0 },
  sheet: { width: '100%', maxWidth: 520, maxHeight: '94%', backgroundColor: '#111114', borderTopLeftRadius: 34, borderTopRightRadius: 34, padding: 18, paddingTop: 10, borderWidth: 1, borderColor: colors.glassBorder },
  sheetHandle: { width: 42, height: 5, borderRadius: 3, backgroundColor: '#48484E', alignSelf: 'center', marginBottom: 14 },
  sheetHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 },
  sheetTitleWrap: { flex: 1 },
  sheetKicker: { color: colors.orange, fontFamily: 'IBMPlexMono_600SemiBold', fontSize: 8, letterSpacing: 1.2, marginBottom: 7 },
  sheetTitle: { color: colors.white, fontSize: 31, lineHeight: 34, fontWeight: '900', letterSpacing: -1.4 },
  sheetDescription: { color: colors.muted, fontSize: 13, lineHeight: 19, marginTop: 7 },
  closeButton: { width: 42, height: 42, borderRadius: 21, backgroundColor: colors.glassStrong, alignItems: 'center', justifyContent: 'center' },
  closeButtonText: { color: colors.white, fontSize: 27, lineHeight: 29 },
  optionTitle: { color: colors.white, fontSize: 18, fontWeight: '900', marginTop: 22, marginBottom: 10 },
  optionRow: { flexDirection: 'row', gap: 8 },
  option: { flex: 1, minHeight: 70, borderRadius: 19, backgroundColor: colors.glass, padding: 12, borderWidth: 1, borderColor: colors.glassBorder },
  optionActive: { borderColor: colors.orange, backgroundColor: 'rgba(255,75,24,0.12)' },
  optionLabel: { color: colors.white, fontSize: 13, fontWeight: '800' },
  optionPrice: { color: colors.muted, fontFamily: 'IBMPlexMono_500Medium', fontSize: 10, marginTop: 5 },
  extraRow: { minHeight: 62, borderRadius: 19, backgroundColor: colors.glass, borderWidth: 1, borderColor: colors.glassBorder, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, marginBottom: 8 },
  extraLabel: { color: colors.white, fontSize: 14, fontWeight: '700' },
  check: { minWidth: 46, height: 34, borderRadius: 17, backgroundColor: colors.glassStrong, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 9 },
  checkActive: { backgroundColor: colors.aqua },
  checkText: { color: colors.white, fontFamily: 'IBMPlexMono_700Bold', fontSize: 11 },
  cartItems: { gap: 10, marginBottom: 18 },
  cartItem: { minHeight: 142, padding: 10 },
  cartThumb: { width: 105, height: 120, borderRadius: 18, backgroundColor: '#34343A', overflow: 'hidden' },
  cartThumbImage: { width: '100%', height: '120%' },
  cartItemCopy: { flex: 1, alignSelf: 'stretch', padding: 8, paddingLeft: 13 },
  cartItemName: { color: colors.white, fontSize: 17, fontWeight: '900' },
  cartItemDetails: { color: colors.muted, fontSize: 11, lineHeight: 16, marginTop: 5 },
  cartItemPrice: { color: colors.white, fontFamily: 'IBMPlexMono_700Bold', fontSize: 13, marginTop: 'auto' },
  counter: { alignItems: 'center', gap: 5 },
  counterButton: { width: 34, height: 34, borderRadius: 17, backgroundColor: colors.glassStrong, alignItems: 'center', justifyContent: 'center' },
  counterText: { color: colors.white, fontSize: 20, lineHeight: 22 },
  counterValue: { color: colors.white, fontFamily: 'IBMPlexMono_700Bold', fontSize: 12 },
  summaryCard: { padding: 18, marginTop: 10 },
  summaryColumn: { flex: 1 },
  summaryRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 6 },
  summaryLabel: { color: colors.muted, fontSize: 13 },
  summaryValue: { color: colors.white, fontFamily: 'IBMPlexMono_600SemiBold', fontSize: 12 },
  freeText: { color: colors.aqua, fontFamily: 'IBMPlexMono_700Bold', fontSize: 11 },
  summaryTotalRow: { borderTopWidth: 1, borderTopColor: colors.glassBorder, paddingTop: 14, marginTop: 5 },
  summaryTotalLabel: { color: colors.white, fontSize: 18, fontWeight: '900' },
  summaryTotalValue: { color: colors.white, fontFamily: 'IBMPlexMono_700Bold', fontSize: 18 },
  bottomAction: { position: 'absolute', left: 0, right: 0, bottom: 0, padding: 18, paddingTop: 6, backgroundColor: 'rgba(11,11,13,0.96)' },
  checkoutHeading: { color: colors.white, fontSize: 21, fontWeight: '900', letterSpacing: -0.7, marginTop: 10, marginBottom: 10 },
  checkoutCard: { minHeight: 78, padding: 13 },
  timeGrid: { flexDirection: 'row', gap: 8 },
  timeChip: { flex: 1, minHeight: 62, borderRadius: 19, backgroundColor: colors.glass, borderWidth: 1, borderColor: colors.glassBorder, alignItems: 'center', justifyContent: 'center' },
  timeChipActive: { backgroundColor: colors.white, borderColor: colors.white },
  timeChipText: { color: colors.white, fontFamily: 'IBMPlexMono_600SemiBold', fontSize: 9, textAlign: 'center' },
  timeChipTextActive: { color: colors.ink },
  paymentCard: { minHeight: 80, padding: 13 },
  cardIcon: { width: 50, height: 50, borderRadius: 17, alignItems: 'center', justifyContent: 'center' },
  cardIconText: { color: colors.ink, fontSize: 24 },
  paymentTitle: { color: colors.white, fontSize: 15, fontWeight: '900' },
  paymentSubtitle: { color: colors.muted, fontFamily: 'IBMPlexMono_500Medium', fontSize: 8.5, marginTop: 4 },
  paymentNotice: { color: colors.muted, fontSize: 11, lineHeight: 16, marginTop: 9, paddingHorizontal: 4 },
  successPage: { flex: 1, padding: 28, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  successGlow: { position: 'absolute', width: 420, height: 420, borderRadius: 210, backgroundColor: 'rgba(255,255,255,0.10)', top: -180, right: -160 },
  successMark: { width: 104, height: 104, borderRadius: 52, backgroundColor: colors.white, alignItems: 'center', justifyContent: 'center', marginBottom: 24 },
  successEyebrow: { color: 'rgba(255,255,255,0.72)', fontFamily: 'IBMPlexMono_700Bold', fontSize: 9, letterSpacing: 1.5 },
  successTitle: { color: colors.white, fontSize: 52, lineHeight: 49, fontWeight: '900', letterSpacing: -3, textAlign: 'center', marginTop: 10 },
  successText: { color: 'rgba(255,255,255,0.8)', fontSize: 14, textAlign: 'center', marginTop: 18 },
  successAddress: { color: colors.white, fontSize: 17, fontWeight: '900', textAlign: 'center', marginTop: 7 },
  statusTrack: { width: '100%', height: 6, borderRadius: 3, backgroundColor: 'rgba(255,255,255,0.28)', marginTop: 36, overflow: 'hidden' },
  statusTrackFilled: { width: '22%', height: '100%', backgroundColor: colors.white, borderRadius: 3 },
  statusLabels: { width: '100%', flexDirection: 'row', justifyContent: 'space-between', marginTop: 9 },
  statusActive: { color: colors.white, fontFamily: 'IBMPlexMono_700Bold', fontSize: 9 },
  statusMuted: { color: 'rgba(255,255,255,0.64)', fontFamily: 'IBMPlexMono_500Medium', fontSize: 9 },
  successButton: { minHeight: 60, width: '100%', borderRadius: 21, backgroundColor: colors.white, alignItems: 'center', justifyContent: 'center', marginTop: 42 },
  successButtonText: { color: colors.ink, fontSize: 15, fontWeight: '900' },
});
